const express=require('express'); const {authenticate,requireRole,requireCompanyAdmin}=require('../middleware/auth'); const asyncHandler=require('../utils/asyncHandler'); const {sendError,sendSuccess}=require('../utils/http'); const {logAuditTrail}=require('../services/auditTrailService'); const {vnMrvService}=require('../services/vnMrvService');
const router=express.Router(); router.use(authenticate); router.use(requireRole('b2b'));
function blocked(res,item,notFound='NO_COMPANY'){if(!item)return sendError(res,{status:404,code:notFound,message:'Record or active company not found.'});if(item.blocked)return sendError(res,{status:422,code:item.code,message:item.message,details:item.details});return null;}
router.get('/cases',asyncHandler(async(req,res)=>{const x=await vnMrvService.listCases(req.companyId);return blocked(res,x)||sendSuccess(res,{data:x});}));
router.post('/cases',requireCompanyAdmin,asyncHandler(async(req,res)=>{const x=await vnMrvService.createCase(req.companyId,req.userId,req.body);const stop=blocked(res,x);if(stop)return stop;await logAuditTrail({companyId:req.companyId,userId:req.userId,dataGroup:'vn_mrv',changedField:'case.revision_created',newValue:x.id,reason:'g2.vn_mrv_case_created',notes:x.caseReference});return sendSuccess(res,{status:201,data:x});}));
router.post('/measurement-plans',requireCompanyAdmin,asyncHandler(async(req,res)=>{const x=await vnMrvService.createPlan(req.companyId,req.userId,req.body);const stop=blocked(res,x,'VN_MRV_CASE_NOT_FOUND');if(stop)return stop;await logAuditTrail({companyId:req.companyId,userId:req.userId,dataGroup:'vn_mrv',changedField:'measurement_plan.revision_created',newValue:x.id,reason:'g2.vn_mrv_plan_created',notes:x.planReference});return sendSuccess(res,{status:201,data:x});}));
router.get('/measurement-plans',asyncHandler(async(req,res)=>{const x=await vnMrvService.listPlans(req.companyId);return blocked(res,x)||sendSuccess(res,{data:x});}));
router.get('/filings',asyncHandler(async(req,res)=>{const x=await vnMrvService.listFilings(req.companyId);return blocked(res,x)||sendSuccess(res,{data:x});}));
router.post('/filings',requireCompanyAdmin,asyncHandler(async(req,res)=>{const x=await vnMrvService.prepareFiling(req.companyId,req.userId,req.body);const stop=blocked(res,x,'VN_MRV_REFERENCE_NOT_FOUND');if(stop)return stop;await logAuditTrail({companyId:req.companyId,userId:req.userId,dataGroup:'vn_mrv',changedField:'filing.snapshot_created',newValue:x.id,reason:'g2.vn_mrv_filing_prepared',notes:x.readinessStatus});return sendSuccess(res,{status:201,data:x});}));
module.exports=router;
