const crypto = require('crypto');

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SOURCES = Object.freeze([
  { id: 'IPCC-2006-METAL', title: '2006 IPCC Guidelines Volume 3 Chapter 4 Metal Industry Emissions', url: 'https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/3_Volume3/V3_4_Ch4_Metal_Industry.pdf' },
  { id: 'IPCC-2006-MINERAL', title: '2006 IPCC Guidelines Volume 3 Chapter 2 Mineral Industry Emissions', url: 'https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/3_Volume3/V3_2_Ch2_Mineral_Industry.pdf' },
  { id: 'IPCC-2006-CHEMICAL', title: '2006 IPCC Guidelines Volume 3 Chapter 3 Chemical Industry Emissions', url: 'https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/3_Volume3/V3_3_Ch3_Chemical_Industry.pdf' },
  { id: 'GHGP-PRODUCT', title: 'GHG Protocol Product Life Cycle Accounting and Reporting Standard', url: 'https://ghgprotocol.org/product-standard' }
]);
const PACKS = Object.freeze({
  steel: Object.freeze({ id: 'steel', label: 'Steel', version: 'G2-STEEL-PILOT-1.1.0', approvalStatus: 'expert_review_required', processes: ['raw_material', 'coke', 'sinter', 'pellet', 'bf', 'bof', 'eaf', 'rolling'], pilotProcesses: ['bf', 'bof', 'eaf'], requiredCategories: ['process', 'fuel', 'electricity'], requiredFields: ['facilityRevisionId', 'processRevisionId', 'outputTonnes', 'activityLines', 'allocation'], requiredContextFields: [], contextFieldDescriptions: {}, allocationPolicy: 'single_product_100_percent_only', validationRules: ['governed_non_proxy_factors', 'locked_activity_and_production_evidence', 'process_taxonomy_match'], evidenceChecklist: ['production', 'activity', 'factor', 'methodology'], targetMappings: ['domestic_mrv_candidate', 'cbam_goods_scope_check_required'], sources: [SOURCES[0], SOURCES[3]] }),
  cement: Object.freeze({ id: 'cement', label: 'Cement', version: 'G2-CEMENT-PILOT-1.1.0', approvalStatus: 'expert_review_required', processes: ['raw_meal', 'kiln', 'clinker', 'grinding', 'additives'], pilotProcesses: ['kiln', 'clinker'], requiredCategories: ['process', 'fuel', 'electricity'], requiredFields: ['facilityRevisionId', 'processRevisionId', 'outputTonnes', 'activityLines', 'allocation'], requiredContextFields: [], contextFieldDescriptions: {}, allocationPolicy: 'single_product_100_percent_only', validationRules: ['governed_non_proxy_factors', 'locked_activity_and_production_evidence', 'process_taxonomy_match'], evidenceChecklist: ['production', 'carbonate_or_clinker', 'fuel', 'electricity', 'factor', 'methodology'], targetMappings: ['domestic_mrv_candidate', 'cbam_goods_scope_check_required'], sources: [SOURCES[1], SOURCES[3]] }),
  textile_apparel: Object.freeze({ id: 'textile_apparel', label: 'Textile / Apparel', version: 'G2-TEXTILE-APPAREL-PILOT-1.0.0', approvalStatus: 'expert_review_required', processes: ['spinning', 'weaving', 'knitting', 'dyeing', 'finishing', 'garment'], pilotProcesses: ['spinning', 'weaving', 'knitting', 'dyeing', 'finishing', 'garment'], requiredCategories: ['material', 'fuel', 'electricity'], requiredFields: ['facilityRevisionId', 'processRevisionId', 'outputTonnes', 'activityLines', 'sectorContext', 'allocation'], requiredContextFields: ['batchOrSkuReference', 'materialOrBomReference', 'buyerOrProductBoundary'], contextFieldDescriptions: { batchOrSkuReference: 'Batch, lot or SKU boundary', materialOrBomReference: 'Material or BOM source reference', buyerOrProductBoundary: 'Buyer/PCF/Scope 3/traceability boundary' }, allocationPolicy: 'single_product_100_percent_only', validationRules: ['material_and_bom_context', 'governed_non_proxy_factors', 'locked_activity_and_production_evidence', 'process_taxonomy_match'], evidenceChecklist: ['production', 'material_bom', 'supplier', 'energy', 'product_boundary', 'factor', 'methodology'], targetMappings: ['buyer_pcf_scope3_traceability_candidate', 'domestic_inventory_applicability_check_required'], sources: [SOURCES[3]] }),
  aluminium: Object.freeze({ id: 'aluminium', label: 'Aluminium', version: 'G2-ALUMINIUM-PILOT-1.0.0', approvalStatus: 'expert_review_required', processes: ['alumina', 'smelting', 'casting', 'recycled_input', 'electricity'], pilotProcesses: ['alumina', 'smelting', 'casting'], requiredCategories: ['material', 'process', 'electricity'], requiredFields: ['facilityRevisionId', 'processRevisionId', 'outputTonnes', 'activityLines', 'sectorContext', 'allocation'], requiredContextFields: ['inputMaterialBasis', 'recycledContentPercent', 'electricityBoundary'], contextFieldDescriptions: { inputMaterialBasis: 'Alumina, primary or recycled input basis', recycledContentPercent: 'Documented recycled-content percentage (0–100)', electricityBoundary: 'Electricity source and smelting/casting boundary' }, allocationPolicy: 'single_product_100_percent_only', validationRules: ['recycled_content_range', 'governed_non_proxy_factors', 'locked_activity_and_production_evidence', 'process_taxonomy_match'], evidenceChecklist: ['production', 'alumina_or_recycled_input', 'process', 'electricity', 'factor', 'methodology'], targetMappings: ['facility_product_carbon_candidate', 'cbam_goods_scope_check_required'], sources: [SOURCES[0], SOURCES[3]] }),
  construction_materials: Object.freeze({ id: 'construction_materials', label: 'Construction Materials', version: 'G2-CONSTRUCTION-MATERIALS-PILOT-1.0.0', approvalStatus: 'expert_review_required', processes: ['quarry', 'crushing', 'cutting', 'ceramics', 'glass', 'concrete', 'logistics'], pilotProcesses: ['quarry', 'crushing', 'cutting', 'ceramics', 'glass', 'concrete'], requiredCategories: ['material', 'fuel', 'electricity'], requiredFields: ['facilityRevisionId', 'processRevisionId', 'outputTonnes', 'activityLines', 'sectorContext', 'allocation'], requiredContextFields: ['materialType', 'quarryOrPlantReference', 'logisticsBoundary'], contextFieldDescriptions: { materialType: 'Stone, ceramic, glass, concrete or other material', quarryOrPlantReference: 'Quarry, line or plant boundary', logisticsBoundary: 'Included/excluded inbound and outbound logistics' }, allocationPolicy: 'single_product_100_percent_only', validationRules: ['material_process_context', 'governed_non_proxy_factors', 'locked_activity_and_production_evidence', 'process_taxonomy_match'], evidenceChecklist: ['production', 'raw_material', 'fuel', 'electricity', 'waste', 'logistics', 'factor', 'methodology'], targetMappings: ['domestic_inventory_resource_tracking_candidate', 'buyer_product_data_candidate'], sources: [SOURCES[1], SOURCES[3]] }),
  fertiliser_chemicals: Object.freeze({ id: 'fertiliser_chemicals', label: 'Fertiliser / Chemicals', version: 'G2-FERTILISER-CHEMICALS-PILOT-1.0.0', approvalStatus: 'expert_review_required', processes: ['ammonia', 'nitric_acid', 'urea', 'fertiliser_blending', 'chemical_processing'], pilotProcesses: ['ammonia', 'nitric_acid', 'urea', 'fertiliser_blending', 'chemical_processing'], requiredCategories: ['feedstock', 'process', 'steam', 'electricity'], requiredFields: ['facilityRevisionId', 'processRevisionId', 'outputTonnes', 'activityLines', 'sectorContext', 'allocation'], requiredContextFields: ['productOrIntermediate', 'feedstockBasis', 'processEmissionBasis'], contextFieldDescriptions: { productOrIntermediate: 'Product or intermediate boundary', feedstockBasis: 'Feedstock type, quantity basis and source', processEmissionBasis: 'Process-emission reaction or measurement basis' }, allocationPolicy: 'single_product_100_percent_only', validationRules: ['feedstock_and_process_emission_context', 'governed_non_proxy_factors', 'locked_activity_and_production_evidence', 'process_taxonomy_match'], evidenceChecklist: ['production', 'feedstock', 'process_parameters', 'steam', 'electricity', 'intermediate', 'factor', 'methodology'], targetMappings: ['domestic_inventory_process_emissions_candidate', 'cbam_goods_scope_check_required'], sources: [SOURCES[2], SOURCES[3]] }),
  mining_minerals: Object.freeze({ id: 'mining_minerals', label: 'Mining / Minerals', version: 'G2-MINING-MINERALS-PILOT-1.0.0', approvalStatus: 'expert_review_required', processes: ['extraction', 'crushing', 'beneficiation', 'processing', 'logistics'], pilotProcesses: ['extraction', 'crushing', 'beneficiation', 'processing'], requiredCategories: ['process', 'fuel', 'electricity', 'transport'], requiredFields: ['facilityRevisionId', 'processRevisionId', 'outputTonnes', 'activityLines', 'sectorContext', 'allocation'], requiredContextFields: ['mineralOrOre', 'extractionMethod', 'logisticsBoundary'], contextFieldDescriptions: { mineralOrOre: 'Mineral, ore or concentrate', extractionMethod: 'Open-pit, underground or other extraction method', logisticsBoundary: 'Included/excluded mine-to-plant logistics' }, allocationPolicy: 'single_product_100_percent_only', validationRules: ['extraction_and_logistics_context', 'governed_non_proxy_factors', 'locked_activity_and_production_evidence', 'process_taxonomy_match'], evidenceChecklist: ['production', 'extraction', 'diesel_or_fuel', 'electricity', 'processing', 'logistics', 'factor', 'methodology'], targetMappings: ['facility_resource_intensity_candidate', 'upstream_supplier_evidence_candidate'], sources: [SOURCES[3]] })
});
const DISCLAIMER = 'Pilot calculation for internal specialist review only. No default factors, regulatory filing, CBAM eligibility, certification or independent verification is asserted.';
function text(value) { return String(value ?? '').trim(); }
function object(value) { return value && typeof value === 'object' && !Array.isArray(value) ? value : {}; }
function arr(value) { return Array.isArray(value) ? value : []; }
function stable(value) { if (Array.isArray(value)) return value.map(stable); if (value && typeof value === 'object') return Object.keys(value).sort().reduce((out, key) => { out[key] = stable(value[key]); return out; }, {}); return value; }
function sha(value) { return crypto.createHash('sha256').update(JSON.stringify(stable(value))).digest('hex'); }
function validDate(value) { const parsed = new Date(`${value}T00:00:00Z`); return /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value; }
function normalize(input = {}) {
  return { packId: text(input.packId), facilityRevisionId: text(input.facilityRevisionId), processRevisionId: text(input.processRevisionId),
    studyReference: text(input.studyReference), periodStart: text(input.periodStart), periodEnd: text(input.periodEnd), outputTonnes: Number(input.outputTonnes),
    productReference: text(input.productReference), sectorContext: { ...object(input.sectorContext) }, allocation: object(input.allocation), methodology: object(input.methodology),
    productionEvidenceDocumentIds: [...new Set(arr(input.productionEvidenceDocumentIds).map(text))],
    activityLines: arr(input.activityLines).map((row) => ({ category: text(row.category), sourceReference: text(row.sourceReference), activityQuantity: Number(row.activityQuantity), activityUnit: text(row.activityUnit), factorProposalId: text(row.factorProposalId), evidenceDocumentIds: [...new Set(arr(row.evidenceDocumentIds).map(text))] })) };
}
function validate(input = {}) {
  const value = normalize(input); const pack = PACKS[value.packId]; const errors = [];
  if (!pack) errors.push(`packId must be one of: ${Object.keys(PACKS).join(', ')}.`);
  for (const field of ['facilityRevisionId', 'processRevisionId']) if (!UUID.test(value[field])) errors.push(`${field} must be a UUID.`);
  if (!value.studyReference || value.studyReference.length > 120) errors.push('studyReference is required.');
  if (!validDate(value.periodStart) || !validDate(value.periodEnd) || value.periodEnd < value.periodStart) errors.push('A valid reporting period is required.');
  if (!Number.isFinite(value.outputTonnes) || value.outputTonnes <= 0) errors.push('outputTonnes must be greater than zero.');
  if (!value.productReference || value.productReference.length > 240) errors.push('productReference is required and must not exceed 240 characters.');
  if (value.allocation.method !== 'single_product' || value.allocation.share !== 1) errors.push('Pilot allocation only supports an evidenced single-product 100% share; co-products require specialist allocation rules.');
  if (!text(value.methodology.boundary) || text(value.methodology.boundary).length > 4000 || !text(value.methodology.source) || text(value.methodology.source).length > 500) errors.push('Methodology boundary and source are required and must stay within their limits.');
  if (pack) {
    const allowedContextFields = new Set(pack.requiredContextFields);
    const extraContextFields = Object.keys(value.sectorContext).filter((field) => !allowedContextFields.has(field));
    if (extraContextFields.length) errors.push(`Unsupported sectorContext fields: ${extraContextFields.join(', ')}.`);
    for (const field of pack.requiredContextFields) {
      const raw = value.sectorContext[field];
      if (field === 'recycledContentPercent') {
        const percent = Number(raw);
        if (raw === '' || raw === null || raw === undefined || !Number.isFinite(percent) || percent < 0 || percent > 100) errors.push('sectorContext.recycledContentPercent must be 0–100.');
        else value.sectorContext[field] = percent;
      } else if (!text(raw) || text(raw).length > 500) errors.push(`sectorContext.${field} is required and must not exceed 500 characters.`);
      else value.sectorContext[field] = text(raw);
    }
  }
  if (!value.productionEvidenceDocumentIds.length || value.productionEvidenceDocumentIds.length > 100 || value.productionEvidenceDocumentIds.some((id) => !UUID.test(id))) errors.push('1–100 production evidence UUIDs are required.');
  if (!value.activityLines.length || value.activityLines.length > 100) errors.push('1–100 activity lines are required.');
  const categories = new Set(value.activityLines.map((line) => line.category));
  if (pack && pack.requiredCategories.some((category) => !categories.has(category))) errors.push(`The ${pack.id} pilot requires activity categories: ${pack.requiredCategories.join(', ')}.`);
  value.activityLines.forEach((line, index) => {
    if (!['process', 'fuel', 'electricity', 'material', 'feedstock', 'steam', 'transport', 'waste', 'water'].includes(line.category) || !line.sourceReference || line.sourceReference.length > 240 || !Number.isFinite(line.activityQuantity) || line.activityQuantity < 0 || !line.activityUnit || line.activityUnit.length > 100 || !UUID.test(line.factorProposalId) || !line.evidenceDocumentIds.length || line.evidenceDocumentIds.length > 100 || line.evidenceDocumentIds.some((id) => !UUID.test(id))) errors.push(`activityLines[${index}] is incomplete.`);
  });
  return { value, pack, errors };
}
function calculate(value, factors) {
  const byId = new Map(factors.map((factor) => [factor.id, factor])); const findings = []; const lines = value.activityLines.map((line) => {
    const factor = byId.get(line.factorProposalId); const expectedUnit = `kgCO2e/${line.activityUnit}`;
    if (!factor || factor.latest_review_decision !== 'approved_for_release_candidate' || factor.unit !== expectedUnit || factor.is_proxy) findings.push({ code: 'FACTOR_NOT_GOVERNED', sourceReference: line.sourceReference, expectedUnit });
    const kgCo2e = factor && Number.isFinite(Number(factor.factor_value)) ? Number((line.activityQuantity * Number(factor.factor_value)).toFixed(6)) : null;
    return { ...line, factorSnapshot: factor ? { id: factor.id, factorId: factor.factor_id, value: Number(factor.factor_value), unit: factor.unit, payloadSha256: factor.payload_sha256, reviewDecision: factor.latest_review_decision, boundary: factor.boundary, isProxy: factor.is_proxy } : null, kgCo2e };
  });
  if (findings.length) return { status: 'needs_information', findings, lines, totals: null };
  const grossKgCo2e = Number(lines.reduce((total, line) => total + line.kgCo2e, 0).toFixed(6));
  return { status: 'specialist_review_required', findings: [{ code: 'PACK_EXPERT_APPROVAL_PENDING' }, { code: 'FACTOR_BOUNDARY_OVERLAP_REVIEW_REQUIRED' }], lines,
    totals: { grossKgCo2e, grossTco2e: Number((grossKgCo2e / 1000).toFixed(6)), intensityKgCo2ePerTonne: Number((grossKgCo2e / value.outputTonnes).toFixed(6)) } };
}
module.exports = { PACKS, DISCLAIMER, validate, calculate, sha };
